logging:
  level:
    guru: debug

server:
  port: 8081

spring:
  # defaults for this docker image - vromero/activemq-artemis
  artemis:
    user: artemis
    password: simetraehcapa

services:
  beer:
    scheme: http
    host: localhost
    port: 8080
    baseContext: api
    version: v1
    endpoints:
      fetchBeerById: beers/{beerId}
      fetchBeerByUpc: beers/upc/{upc}